pipeline {
   agent any
   environment {
       DISABLE_AUTH = 'true'
   }
   stages {
       stage("Build") {
           environment {
                   ENABLE_AUTH = 'false'
              }
           steps {
               echo env.DISABLE_AUTH
               echo env.ENABLE_AUTH
           }
       }
   }
}
